# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1,3,5"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }})

    strategy:
      matrix:
        config:
          - {os: 'ubuntu-latest', python-version: '3.6'}
          - {os: 'ubuntu-latest', python-version: '3.7'}
          - {os: 'ubuntu-latest', python-version: '3.8'}
          - {os: 'windows-latest', python-version: '3.8'}
          - {os: 'macOS-latest', python-version: '3.8'}
          - {os: 'ubuntu-latest', python-version: '3.9'}
          - {os: 'ubuntu-latest', python-version: '3.10'}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}
    - name: Install dependencies
      run: |
        pip install --editable .
        pip install pytest
    - name: Test with pytest
      if: |
        matrix.config.os != 'ubuntu-latest' ||
        matrix.config.python-version != '3.8'
      run: |
        pytest -m ci
    - name: Test with pytest and coverage
      if: |
        matrix.config.os == 'ubuntu-latest' &&
        matrix.config.python-version == '3.8'
      run: |
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      if: |
        matrix.config.os == 'ubuntu-latest' &&
        matrix.config.python-version == '3.8'
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
